### ISSUE TITLE
hmib Inventory error 500

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_hmib#24]
![Inventory](https://user-images.githubusercontent.com/42470924/76425938-b745f380-6380-11ea-9503-ee3880a2cf86.png)
```

2020/03/11 10:09:12 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'hmib'
--
2020/03/11 10:09:12 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2020/03/11 10:09:12 - ERROR PHP ERROR in Plugin 'hmib': Uncaught Error: Call to undefined function html_escpae() in /var/www/localhost/htdocs/cacti/plugins/hmib/hmib.php:1972 Stack trace: #0 /var/www/localhost/htdocs/cacti/plugins/hmib/hmib.php(87): hmib_software() #1 {main} thrown in file: /var/www/localhost/htdocs/cacti/plugins/hmib/hmib.php on line: 1972


```

**Comment by TheWitness** [comment]
This should be fixed.  Closed if satisfied.

**Comment by jdcoats** [comment]
Thanks!

**Comment by minohc** [comment]
Hi, I still have this issue on Cacti 1.2.14 just installed o Windows Server 2012.
Can you help me?

Here the problem when I click on "invetory" tab:

![image](https://user-images.githubusercontent.com/76953211/103539867-12f5e600-4e99-11eb-89cf-f5edae5c193d.png)

**Comment by minohc** [comment]
Resoved:
04/01/2021 14:36:39 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
04/01/2021 14:36:39 - ERROR PHP ERROR: Uncaught Error: Call to undefined function html_escpae() in C:\Apache24\htdocs\cacti\plugins\hmib\hmib.php:1972 Stack trace: #0 C:\Apache24\htdocs\cacti\plugins\hmib\hmib.php(87): hmib_software() #1 {main} thrown in file: C:\Apache24\htdocs\cacti\plugins\hmib\hmib.php on line: 1972

there is a little error in line 1972: correct html_escpae to html_escape

bye
Mino

**Comment by TheWitness** [comment]
Ouch, that's a bug.

**Comment by TheWitness** [comment]
This has been resolved for a while.
